services:
  postgres:
    image: postgis/postgis:latest
    platform: linux/amd64
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./initdb:/docker-entrypoint-initdb.d
    env_file:
      - ../.env
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    env_file:
      - ../.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - backend
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  backend:
    driver: bridge
