"""empty message

Revision ID: 05b05195247d
Revises: f9ba2b13b2db
Create Date: 2025-11-16 04:17:58.436158

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "05b05195247d"
down_revision: Union[str, Sequence[str], None] = "f9ba2b13b2db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "organization", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "organization", type_="unique")
    # ### end Alembic commands ###
