"""empty message

Revision ID: f9ba2b13b2db
Revises: f65ef774f680
Create Date: 2025-11-16 04:01:34.822837

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "f9ba2b13b2db"
down_revision: Union[str, Sequence[str], None] = "f65ef774f680"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "activity", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "activity", type_="unique")
    # ### end Alembic commands ###
