"""empty message

Revision ID: 4974a94bf6f4
Revises: 79b35f70df0d
Create Date: 2025-11-04 09:37:48.476631

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4974a94bf6f4"
down_revision: Union[str, Sequence[str], None] = "79b35f70df0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_activities_name_parent", "activities", ["name", "parent_id"], unique=True
    )
    op.create_unique_constraint(op.f("uq_buildings_address"), "buildings", ["address"])
    op.create_unique_constraint(
        op.f("uq_organizations_name"), "organizations", ["name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_organizations_name"), "organizations", type_="unique")
    op.drop_constraint(op.f("uq_buildings_address"), "buildings", type_="unique")
    op.drop_index("uq_activities_name_parent", table_name="activities")
    # ### end Alembic commands ###
