"""empty message

Revision ID: 9f7fd525417c
Revises: fb7754ae79bd
Create Date: 2025-11-06 03:58:33.719126

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f7fd525417c"
down_revision: Union[str, Sequence[str], None] = "fb7754ae79bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.Column("oid", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("oid"),
    )
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "api_key",
        sa.Column("key", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("last_used", sa.DateTime(), nullable=True),
        sa.Column("banned_at", sa.DateTime(), nullable=True),
        sa.Column("oid", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.oid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("oid"),
    )
    op.create_index(op.f("ix_api_key_key"), "api_key", ["key"], unique=True)
    op.create_index(op.f("ix_api_key_user_id"), "api_key", ["user_id"], unique=False)
    op.drop_constraint(op.f("activity_parent_id_fkey"), "activity", type_="foreignkey")
    op.create_foreign_key(
        None, "activity", "activity", ["parent_id"], ["oid"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "activity", type_="foreignkey")
    op.create_foreign_key(
        op.f("activity_parent_id_fkey"), "activity", "activity", ["parent_id"], ["oid"]
    )
    op.drop_index(op.f("ix_api_key_user_id"), table_name="api_key")
    op.drop_index(op.f("ix_api_key_key"), table_name="api_key")
    op.drop_table("api_key")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
