"""empty message

Revision ID: d58750be8a0c
Revises: fbaaca1b6699
Create Date: 2025-11-04 09:54:44.445602

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d58750be8a0c"
down_revision: Union[str, Sequence[str], None] = "fbaaca1b6699"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_activities_name_root",
        "activities",
        ["name"],
        unique=True,
        postgresql_where="parent_id IS NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_activities_name_root",
        table_name="activities",
        postgresql_where="parent_id IS NULL",
    )
    # ### end Alembic commands ###
