"""empty message

Revision ID: fbaaca1b6699
Revises: fix_activities_unique
Create Date: 2025-11-04 09:49:41.933649

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fbaaca1b6699"
down_revision: Union[str, Sequence[str], None] = "fix_activities_unique"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activities",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "activities",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.drop_index(
        op.f("uq_activities_name_root"),
        table_name="activities",
        postgresql_where="(parent_id IS NULL)",
    )
    op.add_column(
        "buildings",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "buildings",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "organizations",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "organizations",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "updated_at")
    op.drop_column("organizations", "created_at")
    op.drop_column("buildings", "updated_at")
    op.drop_column("buildings", "created_at")
    op.create_index(
        op.f("uq_activities_name_root"),
        "activities",
        ["name"],
        unique=True,
        postgresql_where="(parent_id IS NULL)",
    )
    op.drop_column("activities", "updated_at")
    op.drop_column("activities", "created_at")
    # ### end Alembic commands ###
